_core:
  default_config_hash: x6bhN6WZwfVUI_LLMvRJIUW_2c26VTaBozbfXmJWmro
seckit_xss:
  csp:
    checkbox: true
    vendor-prefix:
      x: true
      webkit: false
    report-only: false
    default-src: "'self'"
    script-src: "'self' 'unsafe-inline' 'unsafe-eval' fonts.googleapis.com www.gstatic.com https://*.google.com https://*.googletagmanager.com *.google-analytics.com https://tagmanager.google.com https://cdn.popupsmart.com"
    object-src: "'none'"
    style-src: "'self' 'unsafe-inline' https://googletagmanager.com https://tagmanager.google.com fonts.googleapis.com"
    img-src: "'self' data: https://*"
    media-src: "'none'"
    frame-src: "'self' https://*.googletagmanager.com https://bid.g.doubleclick.net https://td.doubleclick.net"
    frame-ancestors: "'self'"
    child-src: "'self'"
    font-src: "'self' data: fonts.gstatic.com"
    connect-src: "'self' https://*"
    report-uri: /report-csp-violation
    upgrade-req: false
    policy-uri: ''
  x_xss:
    seckit_x_xss_option_disable: Disabled
    seckit_x_xss_option_0: '0'
    seckit_x_xss_option_1: 1;
    seckit_x_xss_option_1_block: '1; mode=block'
    select: 0
seckit_csrf:
  origin: true
  origin_whitelist: ''
seckit_clickjacking:
  js_css_noscript: false
  noscript_message: 'Sorry, you need to enable JavaScript to visit this website.'
  x_frame: '1'
  x_frame_allow_from: ''
seckit_ssl:
  hsts: true
  hsts_subdomains: true
  hsts_max_age: 31536000
  hsts_preload: false
seckit_ct:
  expect_ct: false
  max_age: 86400
  report_uri: ''
  enforce: false
seckit_fp:
  feature_policy: false
  feature_policy_policy: ''
seckit_various:
  from_origin: false
  from_origin_destination: same
  referrer_policy: false
  referrer_policy_policy: strict-origin-when-cross-origin
  disable_autocomplete: false
